[system]
description = "Simple system designed to test the initialization protocols. SUCCESS == seeing print outs from components 3 & 4 not interleaved."

[[components]]
name = "print"
img  = "print.serializing"
implements = [{interface = "print"}]
deps = [{srv = "booter", interface = "init"}]
constructor = "booter"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}, {srv = "print", interface = "print"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}, {srv = "print", interface = "print"}]
implements = [{interface = "sched"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "unit1"
img  = "tests.unit_init"
deps = [{srv = "agg", interface = "pong"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "unit2"
img  = "tests.unit_init"
deps = [{srv = "agg", interface = "pong"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "agg"
img  = "pong.init_pong"
deps = [{srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
implements = [{interface = "pong"}]
constructor = "booter"
